baseURL: "http://example.org/"
languageCode: "en-us"
title: "kubeclod.io"
theme: "kubecloud"
params:
  builtBy: "bool"
  defaultImage: "no-image.png"

  facebook: ""
  quora: ""
  twitter: ""
  github: "http://github.com/kubecloud"
  email: ""

  fbLikeBox: ""
  fbAppId: ""
  fbPageUrl: ""
  fbPageTitle: ""

  analytics: ""
  disqus: ""

  copyright:
    name: "kubecloud.io 2020"
    link: "https://kubecloud.io"